baseurl = "http://litmon.github.io/techblog"
languageCode = "ja"
title = "もんの技術実験場"

theme = "hugo-theme-geppaku"

[author]
  name = "Fukuo Kadota"
  twitter = "_litmon_"
  facebook = "fukuo.kadota"
  github = "litmon"

[params]
  [params.sharebutton]
    twitter = true
    facebook = true
